

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    image: "dotnet-dind"  
    build:
      context: .          
    depends_on:
      - rabbitmq          
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      RABBITMQ_HOST: rabbitmq  
    deploy:
      replicas: 5  



