
services:
  judgeapi:
    image: "mrarthur0507/judge-executor:1.0" 
    container_name: judge
    ports:
      - "5900:5900"  
    depends_on:
      - rabbitmq     
    environment:
      RabbitMQ__Host: rabbitmq  
      ASPNETCORE_ENVIRONMENT: Development
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    image: "mrarthur0507/judge-worker:1.0"  
    build:
      context: .
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq  
    deploy:
      replicas: 5  
    privileged: true 

